version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: newtonlaw18/reverseproxy
  backend_user:
    build:
      context: ../../udacity-api-user
    image: newtonlaw18/udacity-api-user
  backend_feed:
    build:
      context: ../../udacity-api-feed
    image: newtonlaw18/udacity-api-feed
  frontend:
    build:
      context: ../../udacity-frontend
    image: newtonlaw18/udacity-frontend:prod
